//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVDCollection.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DvdCollection
    {
        public int FilmID { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public string Actor { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> RunTime { get; set; }
        public string Rating { get; set; }
    }
}
